kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: feature/cbolles/webhook-handler
    app.openshift.io/vcs-uri: 'https://github.com/hicsail/far-frp'
    openshift.io/generated-by: OpenShiftWebConsole
  name: frp-job
  generation: 2
  namespace: sail-24887a
  labels:
    app: frp-roi
    app.kubernetes.io/component: frp-job
    app.kubernetes.io/instance: frp-job
    app.kubernetes.io/name: frp-job
    app.kubernetes.io/part-of: wage-gap-calculator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'frp-job:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/hicsail/far-frp'
      ref: feature/cbolles/webhook-handler
    contextDir: /packages/frp-job
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: wage-gap-calculator-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: wage-gap-calculator-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
