[tool.poetry]
name = "frp"
version = "0.1.0"
description = ""
authors = ["cbolles <collinbolles@gmail.com>"]
readme = "README.md"
packages = [
  { include = "frp" },
  { include = "frp/py.typed" }
]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.2.2"
langchain = "^0.2.4"
langchain-community = "^0.2.4"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
pandas-stubs = "^2.2.2.240603"
flake8 = "^7.0.0"
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
