name: FRP-cli

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/frp-cli/**'
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - 'packages/frp-cli/**'
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check for Linting Errors
    defaults:
      run:
        working-directory: packages/frp-cli

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Lint
        run: poetry run flake8

  build:
    runs-on: ubuntu-latest
    name: Build
    defaults:
      run:
        working-directory: packages/frp-cli

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd ../frp
          poetry install
          cd ../frp-cli
          poetry install --with dev

      - name: Build
        run: poetry build

  type-checking:
    runs-on: ubuntu-latest
    name: Run Type Checking
    defaults:
      run:
        working-directory: packages/frp-cli

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd ../frp
          poetry config virtualenvs.create false
          poetry install
          cd ../frp-cli
          poetry install --with dev

      - name: Type Checking
        run: poetry run mypy frp_cli/
